//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SIC.EntityLayer
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class SICDBWEBEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto SICDBWEBEntities usando la cadena de conexión encontrada en la sección 'SICDBWEBEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public SICDBWEBEntities() : base("name=SICDBWEBEntities", "SICDBWEBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SICDBWEBEntities.
        /// </summary>
        public SICDBWEBEntities(string connectionString) : base(connectionString, "SICDBWEBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SICDBWEBEntities.
        /// </summary>
        public SICDBWEBEntities(EntityConnection connection) : base(connection, "SICDBWEBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Importaciones de funciones
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="cLI_C_BGRUPO_IBK">No hay documentación de metadatos disponible.</param>
        /// <param name="cLI_C_VRAZ_SOC">No hay documentación de metadatos disponible.</param>
        /// <param name="cLI_C_VDOC_ID">No hay documentación de metadatos disponible.</param>
        public int SIC_SP_CLIENTE_LISTAR(Nullable<global::System.Byte> cLI_C_BGRUPO_IBK, global::System.String cLI_C_VRAZ_SOC, global::System.String cLI_C_VDOC_ID)
        {
            ObjectParameter cLI_C_BGRUPO_IBKParameter;
            if (cLI_C_BGRUPO_IBK.HasValue)
            {
                cLI_C_BGRUPO_IBKParameter = new ObjectParameter("CLI_C_BGRUPO_IBK", cLI_C_BGRUPO_IBK);
            }
            else
            {
                cLI_C_BGRUPO_IBKParameter = new ObjectParameter("CLI_C_BGRUPO_IBK", typeof(global::System.Byte));
            }
    
            ObjectParameter cLI_C_VRAZ_SOCParameter;
            if (cLI_C_VRAZ_SOC != null)
            {
                cLI_C_VRAZ_SOCParameter = new ObjectParameter("CLI_C_VRAZ_SOC", cLI_C_VRAZ_SOC);
            }
            else
            {
                cLI_C_VRAZ_SOCParameter = new ObjectParameter("CLI_C_VRAZ_SOC", typeof(global::System.String));
            }
    
            ObjectParameter cLI_C_VDOC_IDParameter;
            if (cLI_C_VDOC_ID != null)
            {
                cLI_C_VDOC_IDParameter = new ObjectParameter("CLI_C_VDOC_ID", cLI_C_VDOC_ID);
            }
            else
            {
                cLI_C_VDOC_IDParameter = new ObjectParameter("CLI_C_VDOC_ID", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("SIC_SP_CLIENTE_LISTAR", cLI_C_BGRUPO_IBKParameter, cLI_C_VRAZ_SOCParameter, cLI_C_VDOC_IDParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="iNTCODIGOAREA">No hay documentación de metadatos disponible.</param>
        public ObjectResult<SIC_SP_CLIENTE_LISTAR_COLABORADORES_POR_AREA_Result> SIC_SP_CLIENTE_LISTAR_COLABORADORES_POR_AREA(Nullable<global::System.Byte> iNTCODIGOAREA)
        {
            ObjectParameter iNTCODIGOAREAParameter;
            if (iNTCODIGOAREA.HasValue)
            {
                iNTCODIGOAREAParameter = new ObjectParameter("INTCODIGOAREA", iNTCODIGOAREA);
            }
            else
            {
                iNTCODIGOAREAParameter = new ObjectParameter("INTCODIGOAREA", typeof(global::System.Byte));
            }
    
            return base.ExecuteFunction<SIC_SP_CLIENTE_LISTAR_COLABORADORES_POR_AREA_Result>("SIC_SP_CLIENTE_LISTAR_COLABORADORES_POR_AREA", iNTCODIGOAREAParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="nomb_com_c_vnomb">No hay documentación de metadatos disponible.</param>
        public ObjectResult<Nullable<global::System.Int32>> SIC_SP_NOMBRECOMERCIAL_BUSCAR_EXISTENCIA(global::System.String nomb_com_c_vnomb)
        {
            ObjectParameter nomb_com_c_vnombParameter;
            if (nomb_com_c_vnomb != null)
            {
                nomb_com_c_vnombParameter = new ObjectParameter("nomb_com_c_vnomb", nomb_com_c_vnomb);
            }
            else
            {
                nomb_com_c_vnombParameter = new ObjectParameter("nomb_com_c_vnomb", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Int32>>("SIC_SP_NOMBRECOMERCIAL_BUSCAR_EXISTENCIA", nomb_com_c_vnombParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="cli_c_vdoc_id">No hay documentación de metadatos disponible.</param>
        public ObjectResult<Nullable<global::System.Int32>> ADV_SP_CLIENTE_VERIFICAR_EXISTENCIA(global::System.String cli_c_vdoc_id)
        {
            ObjectParameter cli_c_vdoc_idParameter;
            if (cli_c_vdoc_id != null)
            {
                cli_c_vdoc_idParameter = new ObjectParameter("cli_c_vdoc_id", cli_c_vdoc_id);
            }
            else
            {
                cli_c_vdoc_idParameter = new ObjectParameter("cli_c_vdoc_id", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Int32>>("ADV_SP_CLIENTE_VERIFICAR_EXISTENCIA", cli_c_vdoc_idParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="cli_c_vdoc_id">No hay documentación de metadatos disponible.</param>
        public ObjectResult<Nullable<global::System.Int32>> SIC_SP_CLIENTE_VERIFICAR_EXISTENCIA(global::System.String cli_c_vdoc_id)
        {
            ObjectParameter cli_c_vdoc_idParameter;
            if (cli_c_vdoc_id != null)
            {
                cli_c_vdoc_idParameter = new ObjectParameter("cli_c_vdoc_id", cli_c_vdoc_id);
            }
            else
            {
                cli_c_vdoc_idParameter = new ObjectParameter("cli_c_vdoc_id", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Int32>>("SIC_SP_CLIENTE_VERIFICAR_EXISTENCIA", cli_c_vdoc_idParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="cli_c_vdoc_id">No hay documentación de metadatos disponible.</param>
        public ObjectResult<Nullable<global::System.Int32>> SIC_SP_CLIENTE_DIRECCION_GENERARIDDIRECCION(global::System.String cli_c_vdoc_id)
        {
            ObjectParameter cli_c_vdoc_idParameter;
            if (cli_c_vdoc_id != null)
            {
                cli_c_vdoc_idParameter = new ObjectParameter("cli_c_vdoc_id", cli_c_vdoc_id);
            }
            else
            {
                cli_c_vdoc_idParameter = new ObjectParameter("cli_c_vdoc_id", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Int32>>("SIC_SP_CLIENTE_DIRECCION_GENERARIDDIRECCION", cli_c_vdoc_idParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="cli_c_vdoc_id">No hay documentación de metadatos disponible.</param>
        public int SIC_SP_CLIENTE_NOMBRECOMERCIAL_LIMPIAR(global::System.String cli_c_vdoc_id)
        {
            ObjectParameter cli_c_vdoc_idParameter;
            if (cli_c_vdoc_id != null)
            {
                cli_c_vdoc_idParameter = new ObjectParameter("cli_c_vdoc_id", cli_c_vdoc_id);
            }
            else
            {
                cli_c_vdoc_idParameter = new ObjectParameter("cli_c_vdoc_id", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("SIC_SP_CLIENTE_NOMBRECOMERCIAL_LIMPIAR", cli_c_vdoc_idParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="cHOPCION">No hay documentación de metadatos disponible.</param>
        /// <param name="cLI_C_VDOC_ID">No hay documentación de metadatos disponible.</param>
        /// <param name="cLI_RS_H_C_VRAZ_SOC">No hay documentación de metadatos disponible.</param>
        public int SIC_SP_CLIENTE_MANTENIMIENTO_RAZON_SOCIAL_HISTORICO(global::System.String cHOPCION, global::System.String cLI_C_VDOC_ID, global::System.String cLI_RS_H_C_VRAZ_SOC)
        {
            ObjectParameter cHOPCIONParameter;
            if (cHOPCION != null)
            {
                cHOPCIONParameter = new ObjectParameter("CHOPCION", cHOPCION);
            }
            else
            {
                cHOPCIONParameter = new ObjectParameter("CHOPCION", typeof(global::System.String));
            }
    
            ObjectParameter cLI_C_VDOC_IDParameter;
            if (cLI_C_VDOC_ID != null)
            {
                cLI_C_VDOC_IDParameter = new ObjectParameter("CLI_C_VDOC_ID", cLI_C_VDOC_ID);
            }
            else
            {
                cLI_C_VDOC_IDParameter = new ObjectParameter("CLI_C_VDOC_ID", typeof(global::System.String));
            }
    
            ObjectParameter cLI_RS_H_C_VRAZ_SOCParameter;
            if (cLI_RS_H_C_VRAZ_SOC != null)
            {
                cLI_RS_H_C_VRAZ_SOCParameter = new ObjectParameter("CLI_RS_H_C_VRAZ_SOC", cLI_RS_H_C_VRAZ_SOC);
            }
            else
            {
                cLI_RS_H_C_VRAZ_SOCParameter = new ObjectParameter("CLI_RS_H_C_VRAZ_SOC", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("SIC_SP_CLIENTE_MANTENIMIENTO_RAZON_SOCIAL_HISTORICO", cHOPCIONParameter, cLI_C_VDOC_IDParameter, cLI_RS_H_C_VRAZ_SOCParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="cli_c_vdoc_id">No hay documentación de metadatos disponible.</param>
        public ObjectResult<Nullable<global::System.Int32>> SIC_SP_CLIENTE_CONTAR_RUC(global::System.String cli_c_vdoc_id)
        {
            ObjectParameter cli_c_vdoc_idParameter;
            if (cli_c_vdoc_id != null)
            {
                cli_c_vdoc_idParameter = new ObjectParameter("cli_c_vdoc_id", cli_c_vdoc_id);
            }
            else
            {
                cli_c_vdoc_idParameter = new ObjectParameter("cli_c_vdoc_id", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Int32>>("SIC_SP_CLIENTE_CONTAR_RUC", cli_c_vdoc_idParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="cli_c_vdoc_id">No hay documentación de metadatos disponible.</param>
        /// <param name="nomb_com_c_iid">No hay documentación de metadatos disponible.</param>
        public int SIC_SP_CLIENTE_NOMBRE_REGISTRAR(global::System.String cli_c_vdoc_id, Nullable<global::System.Int32> nomb_com_c_iid)
        {
            ObjectParameter cli_c_vdoc_idParameter;
            if (cli_c_vdoc_id != null)
            {
                cli_c_vdoc_idParameter = new ObjectParameter("cli_c_vdoc_id", cli_c_vdoc_id);
            }
            else
            {
                cli_c_vdoc_idParameter = new ObjectParameter("cli_c_vdoc_id", typeof(global::System.String));
            }
    
            ObjectParameter nomb_com_c_iidParameter;
            if (nomb_com_c_iid.HasValue)
            {
                nomb_com_c_iidParameter = new ObjectParameter("nomb_com_c_iid", nomb_com_c_iid);
            }
            else
            {
                nomb_com_c_iidParameter = new ObjectParameter("nomb_com_c_iid", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("SIC_SP_CLIENTE_NOMBRE_REGISTRAR", cli_c_vdoc_idParameter, nomb_com_c_iidParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region ComplexTypes
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SICDBWEBModel", Name="SIC_SP_CLIENTE_LISTAR_COLABORADORES_POR_AREA_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SIC_SP_CLIENTE_LISTAR_COLABORADORES_POR_AREA_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto SIC_SP_CLIENTE_LISTAR_COLABORADORES_POR_AREA_Result.
        /// </summary>
        /// <param name="colab_c_cdoc_id">Valor inicial de la propiedad colab_c_cdoc_id.</param>
        public static SIC_SP_CLIENTE_LISTAR_COLABORADORES_POR_AREA_Result CreateSIC_SP_CLIENTE_LISTAR_COLABORADORES_POR_AREA_Result(global::System.String colab_c_cdoc_id)
        {
            SIC_SP_CLIENTE_LISTAR_COLABORADORES_POR_AREA_Result sIC_SP_CLIENTE_LISTAR_COLABORADORES_POR_AREA_Result = new SIC_SP_CLIENTE_LISTAR_COLABORADORES_POR_AREA_Result();
            sIC_SP_CLIENTE_LISTAR_COLABORADORES_POR_AREA_Result.colab_c_cdoc_id = colab_c_cdoc_id;
            return sIC_SP_CLIENTE_LISTAR_COLABORADORES_POR_AREA_Result;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String colab_c_cdoc_id
        {
            get
            {
                return _colab_c_cdoc_id;
            }
            set
            {
                Oncolab_c_cdoc_idChanging(value);
                ReportPropertyChanging("colab_c_cdoc_id");
                _colab_c_cdoc_id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("colab_c_cdoc_id");
                Oncolab_c_cdoc_idChanged();
            }
        }
        private global::System.String _colab_c_cdoc_id;
        partial void Oncolab_c_cdoc_idChanging(global::System.String value);
        partial void Oncolab_c_cdoc_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String colab_c_cusu_red
        {
            get
            {
                return _colab_c_cusu_red;
            }
            set
            {
                Oncolab_c_cusu_redChanging(value);
                ReportPropertyChanging("colab_c_cusu_red");
                _colab_c_cusu_red = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("colab_c_cusu_red");
                Oncolab_c_cusu_redChanged();
            }
        }
        private global::System.String _colab_c_cusu_red;
        partial void Oncolab_c_cusu_redChanging(global::System.String value);
        partial void Oncolab_c_cusu_redChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String colab_c_vnomb
        {
            get
            {
                return _colab_c_vnomb;
            }
            set
            {
                Oncolab_c_vnombChanging(value);
                ReportPropertyChanging("colab_c_vnomb");
                _colab_c_vnomb = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("colab_c_vnomb");
                Oncolab_c_vnombChanged();
            }
        }
        private global::System.String _colab_c_vnomb;
        partial void Oncolab_c_vnombChanging(global::System.String value);
        partial void Oncolab_c_vnombChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String colab_c_vnomb_completo
        {
            get
            {
                return _colab_c_vnomb_completo;
            }
            set
            {
                Oncolab_c_vnomb_completoChanging(value);
                ReportPropertyChanging("colab_c_vnomb_completo");
                _colab_c_vnomb_completo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("colab_c_vnomb_completo");
                Oncolab_c_vnomb_completoChanged();
            }
        }
        private global::System.String _colab_c_vnomb_completo;
        partial void Oncolab_c_vnomb_completoChanging(global::System.String value);
        partial void Oncolab_c_vnomb_completoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String colab_c_vape_pat
        {
            get
            {
                return _colab_c_vape_pat;
            }
            set
            {
                Oncolab_c_vape_patChanging(value);
                ReportPropertyChanging("colab_c_vape_pat");
                _colab_c_vape_pat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("colab_c_vape_pat");
                Oncolab_c_vape_patChanged();
            }
        }
        private global::System.String _colab_c_vape_pat;
        partial void Oncolab_c_vape_patChanging(global::System.String value);
        partial void Oncolab_c_vape_patChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String colab_c_vape_mat
        {
            get
            {
                return _colab_c_vape_mat;
            }
            set
            {
                Oncolab_c_vape_matChanging(value);
                ReportPropertyChanging("colab_c_vape_mat");
                _colab_c_vape_mat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("colab_c_vape_mat");
                Oncolab_c_vape_matChanged();
            }
        }
        private global::System.String _colab_c_vape_mat;
        partial void Oncolab_c_vape_matChanging(global::System.String value);
        partial void Oncolab_c_vape_matChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String colab_c_vpass
        {
            get
            {
                return _colab_c_vpass;
            }
            set
            {
                Oncolab_c_vpassChanging(value);
                ReportPropertyChanging("colab_c_vpass");
                _colab_c_vpass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("colab_c_vpass");
                Oncolab_c_vpassChanged();
            }
        }
        private global::System.String _colab_c_vpass;
        partial void Oncolab_c_vpassChanging(global::System.String value);
        partial void Oncolab_c_vpassChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> colab_area_c_yid
        {
            get
            {
                return _colab_area_c_yid;
            }
            set
            {
                Oncolab_area_c_yidChanging(value);
                ReportPropertyChanging("colab_area_c_yid");
                _colab_area_c_yid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("colab_area_c_yid");
                Oncolab_area_c_yidChanged();
            }
        }
        private Nullable<global::System.Byte> _colab_area_c_yid;
        partial void Oncolab_area_c_yidChanging(Nullable<global::System.Byte> value);
        partial void Oncolab_area_c_yidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> colab_cargo_c_yid
        {
            get
            {
                return _colab_cargo_c_yid;
            }
            set
            {
                Oncolab_cargo_c_yidChanging(value);
                ReportPropertyChanging("colab_cargo_c_yid");
                _colab_cargo_c_yid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("colab_cargo_c_yid");
                Oncolab_cargo_c_yidChanged();
            }
        }
        private Nullable<global::System.Byte> _colab_cargo_c_yid;
        partial void Oncolab_cargo_c_yidChanging(Nullable<global::System.Byte> value);
        partial void Oncolab_cargo_c_yidChanged();

        #endregion
    }

    #endregion
    
}
